### ISSUE TITLE
Package as flatpak or appimage

### ISSUE THREAD

**Issue by Twig6943** [rednik1337/CheatTurbine#1]
title.

**Comment by rednik1337** [comment]
[done](https://github.com/rednik1337/CheatTurbine?tab=readme-ov-file#downloading-the-binary)

**Comment by Twig6943** [comment]
> [done](https://github.com/rednik1337/CheatTurbine?tab=readme-ov-file#downloading-the-binary)

@rednik1337 could u make it so that the appimages get uploaded to the releases tab

**Comment by rednik1337** [comment]
I don't think it's a good idea to make a new release with every single commit. Once I get the project to a stable enough state, I'll make a release. However, I don't think that will happen anytime soon, given the little to no time I have for the project
